CREATE TABLE USER_LOGIN(
	USERNAME VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(100),
    PASSWD VARCHAR(50) NOT NULL,
    POINTS NUMERIC DEFAULT 0,
    PRIMARY KEY(EMAIL)
);

CREATE TABLE PRODUCTS(
	PRODUCT_ID VARCHAR(30) NOT NULL,
    PRODUCT_DESC VARCHAR(500) NOT NULL,
    PRODUCT_NAME VARCHAR(60) NOT NULL,
    PRODUCT_PRICE NUMERIC NOT NULL CHECK(PRODUCT_PRICE>0),
    POINT_PER_UNIT NUMERIC DEFAULT 0,
    PRODUCT_RATING NUMERIC DEFAULT 0,
    PRODUCT_LINK VARCHAR(500) NOT NULL,
    NO_OF_SOLD INTEGER DEFAULT 0 CHECK(NO_OF_SOLD>=0),
    CATEGORY VARCHAR(50) NOT NULL,
    PRIMARY KEY(PRODUCT_ID)
);

CREATE TABLE IMAGES(
	PRODUCT_ID VARCHAR(30) REFERENCES PRODUCTS(PRODUCT_ID),
	IMAGE_LINK VARCHAR(500)
);

CREATE TABLE REWARDS(
	REWARD_ID VARCHAR(30) NOT NULL,
    PRODUCT_DESC VARCHAR(500) NOT NULL,
    PRODUCT_NAME VARCHAR(60) NOT NULL,
    PRODUCT_POINTS NUMERIC NOT NULL CHECK(PRODUCT_POINTS>0),
    PRODUCT_LINK VARCHAR(500) NOT NULL,
    NO_OF_SOLD INTEGER DEFAULT 0,
    PRIMARY KEY(REWARD_ID)
);

CREATE TABLE PURCHASES(
	PURCHASE_ID VARCHAR(50) NOT NULL,
    PRODUCT_ID VARCHAR(30) REFERENCES PRODUCTS(PRODUCT_ID),
    USER_ID VARCHAR(100) REFERENCES USER_LOGIN(EMAIL),
    PURCHASE_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY(PURCHASE_ID)
);

CREATE TABLE ORDERS(
	ORDER_ID VARCHAR(50) NOT NULL,
    PRODUCT_ID VARCHAR(30) REFERENCES PRODUCTS(PRODUCT_ID),
	USER_ID VARCHAR(100) REFERENCES USER_LOGIN(EMAIL),
    DATE_OF_ORDER TIMESTAMP NOT NULL,
    PRICE NUMERIC NOT NULL,
    POINTS_GAINED NUMERIC DEFAULT 0,
    ARRIVAL_STATUS VARCHAR(50) NOT NULL,
    PRIMARY KEY(ORDER_ID)
);

CREATE TABLE TRANSACTIONS(
	ORDER_ID VARCHAR(50) REFERENCES ORDERS(ORDER_ID),
	PRODUCT_ID VARCHAR(30) REFERENCES PRODUCTS(PRODUCT_ID),
    USER_ID VARCHAR(100) REFERENCES USER_LOGIN(EMAIL),
    TRANSACTION_DATE TIMESTAMP NOT NULL,
    TRANSACTION_AMOUNT NUMERIC NOT NULL,
    PAYMENT_METHOD VARCHAR(50) NOT NULL
);

CREATE TABLE CART(
	PRODUCT_ID VARCHAR(30) REFERENCES PRODUCTS(PRODUCT_ID),
	QUANTITY NUMERIC DEFAULT 0,
    TOTAL_PRICE NUMERIC DEFAULT 0
);

CREATE TABLE PROMOTIONS(
	PRODUCT_ID VARCHAR(30) REFERENCES PRODUCTS(PRODUCT_ID),
    PROMOTION_QUOTE VARCHAR(500) NOT NULL,
    VALIDITY_PERIOD TIMESTAMP NOT NULL,
    DISCOUNT_AMT NUMERIC DEFAULT 0
);

CREATE TABLE WISH_LIST(
	WISH_ID VARCHAR(50) PRIMARY KEY,
	PRODUCT_ID VARCHAR(30) REFERENCES PRODUCTS(PRODUCT_ID),
    USER_ID VARCHAR(100) REFERENCES USER_LOGIN(EMAIL),
    PRIORITY INTEGER DEFAULT 0,
);